include:
  - docker-compose.domain.yml
  - docker-compose.particular.yml
  - ./platform/fileprocessing/docker-compose.fileprocessing.yml # File Processing API and Worker
  - ./platform/fileprocessing/docker-compose.test-services.yml
