param(
    [string]$ApiBaseUrl = "http://127.0.0.1:7090",
    [string]$ClientId = "",
    [string]$BearerToken = "",
    [string]$JwtSecret = "",
    [string]$JwtIssuer = "",
    [string]$JwtAudience = "",
    [string]$ConfigurationName = "HTTP NACHA Daily Scan"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function ConvertTo-Base64Url {
    param([byte[]]$Bytes)

    $value = [Convert]::ToBase64String($Bytes)
    $value = $value.TrimEnd('=')
    $value = $value.Replace('+', '-')
    $value = $value.Replace('/', '_')
    return $value
}

function New-JwtToken {
    param(
        [Parameter(Mandatory = $true)][string]$Secret,
        [Parameter(Mandatory = $true)][string]$Issuer,
        [Parameter(Mandatory = $true)][string]$Audience,
        [Parameter(Mandatory = $true)][string]$ClientId
    )

    $now = [int][Math]::Floor(([DateTimeOffset]::UtcNow.ToUnixTimeSeconds()))

    $headerJson = '{"alg":"HS256","typ":"JWT"}'
    $payloadObject = [ordered]@{
        sub       = "e2e-test-user"
        client_id = $ClientId
        iss       = $Issuer
        aud       = $Audience
        iat       = $now
        nbf       = $now
        exp       = $now + (30 * 60)
        jti       = "$ClientId-$now"
    }

    $payloadJson = $payloadObject | ConvertTo-Json -Compress

    $headerEncoded = ConvertTo-Base64Url ([Text.Encoding]::UTF8.GetBytes($headerJson))
    $payloadEncoded = ConvertTo-Base64Url ([Text.Encoding]::UTF8.GetBytes($payloadJson))
    $unsigned = "$headerEncoded.$payloadEncoded"

    $hmac = [System.Security.Cryptography.HMACSHA256]::new([Text.Encoding]::UTF8.GetBytes($Secret))
    try {
        $signatureBytes = $hmac.ComputeHash([Text.Encoding]::UTF8.GetBytes($unsigned))
    }
    finally {
        $hmac.Dispose()
    }

    $signatureEncoded = ConvertTo-Base64Url $signatureBytes
    return "$unsigned.$signatureEncoded"
}

if ([string]::IsNullOrWhiteSpace($ClientId)) {
    $ClientId = "e2e-client-$([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds())"
}

if ([string]::IsNullOrWhiteSpace($BearerToken)) {
    $BearerToken = $env:FILE_RETRIEVAL_BEARER_TOKEN
}

if ([string]::IsNullOrWhiteSpace($BearerToken)) {
    if ([string]::IsNullOrWhiteSpace($JwtSecret)) {
        $JwtSecret = if ([string]::IsNullOrWhiteSpace($env:FILE_RETRIEVAL_JWT_SECRET)) { "REPLACE_WITH_SECRET_KEY_AT_LEAST_32_CHARS_LONG_FOR_PRODUCTION" } else { $env:FILE_RETRIEVAL_JWT_SECRET }
    }
    if ([string]::IsNullOrWhiteSpace($JwtIssuer)) {
        $JwtIssuer = if ([string]::IsNullOrWhiteSpace($env:FILE_RETRIEVAL_JWT_ISSUER)) { "https://riskinsure.com" } else { $env:FILE_RETRIEVAL_JWT_ISSUER }
    }
    if ([string]::IsNullOrWhiteSpace($JwtAudience)) {
        $JwtAudience = if ([string]::IsNullOrWhiteSpace($env:FILE_RETRIEVAL_JWT_AUDIENCE)) { "file-retrieval-api" } else { $env:FILE_RETRIEVAL_JWT_AUDIENCE }
    }

    $BearerToken = New-JwtToken -Secret $JwtSecret -Issuer $JwtIssuer -Audience $JwtAudience -ClientId $ClientId
}

$endpoint = ($ApiBaseUrl.TrimEnd('/')) + "/api/v1/configuration"

# PublishNachaFile.ps1 generates filenames like: sample_yyyyMMdd_HHmmss.ach
# This pattern matches files for the current day/month/year only.
$payload = [ordered]@{
    name = $ConfigurationName
    description = "Checks HTTPS location every 5 minutes for today's NACHA files generated by PublishNachaFile.ps1"
    protocol = "Https"
    protocolSettings = [ordered]@{
        BaseUrl = "https://file-retrieval-https:443/"
        AuthenticationType = "None"
        ConnectionTimeoutSeconds = 30
        FollowRedirects = $true
        MaxRedirects = 3
    }
    filePathPattern = "/"
    filenamePattern = "sample_{yyyy}{mm}{dd}_*.ach"
    fileExtension = "ach"
    schedule = [ordered]@{
        cronExpression = "0 */5 * * * *"
        timezone = "UTC"
        description = "Every 5 minutes"
    }
    processingConfig = [ordered]@{
        fileType = "NACHA"
    }
}

$headers = @{
    Authorization = "Bearer $BearerToken"
}

Write-Host "Creating FileRetrieval configuration at: $endpoint"
$response = Invoke-RestMethod -Method Post -Uri $endpoint -Headers $headers -ContentType "application/json" -Body ($payload | ConvertTo-Json -Depth 10)

Write-Host "Configuration request accepted."
$response | ConvertTo-Json -Depth 10
