using NServiceBus;
using FileRetrieval.Contracts.DTOs;

namespace FileRetrieval.Contracts.Commands;

/// <summary>
/// Command to create a new FileRetrievalConfiguration.
/// Sent by API Controller, handled by CreateConfigurationHandler.
/// </summary>
public record CreateConfiguration : ICommand
{
    public Guid MessageId { get; init; }
    public required string CorrelationId { get; init; }
    public DateTimeOffset OccurredUtc { get; init; }
    public required string IdempotencyKey { get; init; }
    
    // Configuration details
    public required string ClientId { get; init; }
    public Guid ConfigurationId { get; init; } // Pre-generated by API
    public required string Name { get; init; }
    public string? Description { get; init; }
    public required string Protocol { get; init; } // "Ftp", "Https", "AzureBlob"
    public required Dictionary<string, object> ProtocolSettings { get; init; }
    public required string FilePathPattern { get; init; }
    public required string FilenamePattern { get; init; }
    public string? FileExtension { get; init; }
    public required ScheduleDefinitionDto Schedule { get; init; }
    public required List<EventDefinitionDto> EventsToPublish { get; init; }
    public List<CommandDefinitionDto>? CommandsToSend { get; init; }
    public required string CreatedBy { get; init; } // User ID from JWT claims
}
